export const CATEGORIES = [
  "Electronics",
  "Home & Living",
  "Health & Beauty",
  "Food & Beverages",
  "Men's Fashion",
  "Women's Fashion",
  "Sports & Outdoors",
  "Automotive",
  "Books & Stationery",
  "Kids & Toys",
  "Groceries",
  "Digital Goods",
  "Travel & Leisure",
  "Vouchers & Services",
  "Tools & Gardening",
  "Pet Supplies",
  "Hardware & Building Materials",
  "Home Appliances",
  "Mobile & Gadgets",
  "Home Improvement",
  "Home Entertainment",
  "Computer & Accessories",
  "Camera & Accessories",
  "Home & Living",
];
